package org.enums;

public enum Menus {
    NAV(null),
        ACASA(NAV),
        DESPRE_NOI(NAV),
        SERVICII(NAV),
            TRATAMENTE_FACIALE(SERVICII),
                MEZOTERAPIE_VIRTUALA(TRATAMENTE_FACIALE),
                TERAPIE_CU_OXIGEN(TRATAMENTE_FACIALE),
                MICRONEEDLING_SAU_MEZOTERAPIE_CU_ACE(TRATAMENTE_FACIALE),
                TRATAMENTE_DERMATO_COSMETICE(TRATAMENTE_FACIALE),

    MAKE_UP(SERVICII),
    STILIZARE_SPRANCENE(SERVICII),
    MICROBLADING(SERVICII),
    EPILARE_CU_CEARA_DE_UNICA_FOLOSINTA(SERVICII),
    PROGRAMARI_ONLINE(NAV),
    BLOG(NAV),
    CONTACT(NAV);

    Menus(Menus parent){
    }
}